/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_left = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData take_photo = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData readings = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_v2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotes = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchase = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
