name: magic_hat_task
description: "Test task for Incode Group"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  provider: ^6.0.2
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.0.5
  fpdart: ^0.4.0
  json_annotation: ^4.8.1
  collection: ^1.17.0
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.0
  intl: ^0.18.1
  flutter_screenutil: ^5.7.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.7
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.2
  build_runner: ^2.3.3
  json_serializable: ^6.1.4
  hive_generator:
    git:
      url: https://github.com/yura2000/hive.git
      path: hive_generator
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0


flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/background/

  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/icons/AppIcons.ttf

    - family: Maghfirea
      fonts:
        - asset: fonts/maghfirea/Maghfirea-Regular.ttf
          weight: 400

    - family: Laisha
      fonts:
        - asset: fonts/laisha/Laisha.ttf
          weight: 400

    - family: Raleway
      fonts:
        - asset: fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/raleway/Raleway-Italic.ttf
          style: italic
